version: '3'

services:
  puppeteer:
    image: pluswerk/puppeteer
    volumes:
      - ./:/app/
    working_dir: /app/
    # just run the container doing nothing
    entrypoint: ["sh", "-c", "sleep infinity"]
